"""Initial schema with all domain entities

Revision ID: 259d78cbdfef
Revises: 
Create Date: 2025-11-08 22:08:10.410133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259d78cbdfef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spotify_uri', sa.String(length=255), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_musicbrainz_id'), 'artists', ['musicbrainz_id'], unique=True)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_artists_spotify_uri'), 'artists', ['spotify_uri'], unique=True)
    op.create_table('playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('spotify_uri', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_name'), 'playlists', ['name'], unique=False)
    op.create_index(op.f('ix_playlists_spotify_uri'), 'playlists', ['spotify_uri'], unique=True)
    op.create_table('albums',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('spotify_uri', sa.String(length=255), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=36), nullable=True),
    sa.Column('artwork_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_musicbrainz_id'), 'albums', ['musicbrainz_id'], unique=True)
    op.create_index(op.f('ix_albums_release_year'), 'albums', ['release_year'], unique=False)
    op.create_index(op.f('ix_albums_spotify_uri'), 'albums', ['spotify_uri'], unique=True)
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_index('ix_albums_title_artist', 'albums', ['title', 'artist_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('album_id', sa.String(length=36), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=False),
    sa.Column('spotify_uri', sa.String(length=255), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=36), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_isrc'), 'tracks', ['isrc'], unique=True)
    op.create_index(op.f('ix_tracks_musicbrainz_id'), 'tracks', ['musicbrainz_id'], unique=True)
    op.create_index(op.f('ix_tracks_spotify_uri'), 'tracks', ['spotify_uri'], unique=True)
    op.create_index(op.f('ix_tracks_title'), 'tracks', ['title'], unique=False)
    op.create_index('ix_tracks_title_artist', 'tracks', ['title', 'artist_id'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_path', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_status'), 'downloads', ['status'], unique=False)
    op.create_index('ix_downloads_status_created', 'downloads', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_downloads_track_id'), 'downloads', ['track_id'], unique=True)
    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    op.create_index('ix_playlist_tracks_position', 'playlist_tracks', ['playlist_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlist_tracks_position', table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index(op.f('ix_downloads_track_id'), table_name='downloads')
    op.drop_index('ix_downloads_status_created', table_name='downloads')
    op.drop_index(op.f('ix_downloads_status'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index('ix_tracks_title_artist', table_name='tracks')
    op.drop_index(op.f('ix_tracks_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_spotify_uri'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_musicbrainz_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_isrc'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('ix_albums_title_artist', table_name='albums')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_index(op.f('ix_albums_spotify_uri'), table_name='albums')
    op.drop_index(op.f('ix_albums_release_year'), table_name='albums')
    op.drop_index(op.f('ix_albums_musicbrainz_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_playlists_spotify_uri'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_name'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_artists_spotify_uri'), table_name='artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_musicbrainz_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
